version: "3.9"

services:
  mariadb:
    container_name: mariadb
    image: mariadb:latest  
    restart: always
    networks:
      - inception-network
    volumes:
      - mariadb_data:/var/lib/mysql 
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - 3306:3306 
  nginx:
    container_name: nginx
    image: nginx:alpine:latest
    restart: always
    depends_on:
      - wordpress
    networks:
      - inception-network
    volumes:
      - ./srcs/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./srcs/certs:/etc/nginx/ssl
      - wordpress_data:/var/www/html
    ports:
      - "443:443"
    environment:
      CERTS_KEY: /etc/nginx/ssl/certificate.key
      CERTS_CRT: /etc/nginx/ssl/certificate.crt

  wordpress:
    container_name: wordpress
    image: wordpress:latest 
    restart: always
    networks:
      - inception-network
    volumes:
      - wordpress_data:/var/www/html 
    depends_on:
      - mariadb
    environment:
      WORDPRESS_DB_HOST: mariadb
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}

volumes:
  wordpress_data:  
  mariadb_data:    

networks:
  inception-network:
    driver: bridge
